linode_image                    = "linode/ubuntu18.04"
linode_image_label              = "tfs-linux-node"
Linode_image_group              = "Linux"
linode_image_deployment_region  = "us-east"
linode_image_type               = "g6-standard-1"