linode_image                    = "linode/ubuntu18.04"
linode_image_label              = "Terraform-Web-Example"
Linode_image_group              = "Terraform"
linode_image_deployment_region  = "us-east"
linode_image_type               = "g6-standard-1"