# Comments Generated by ChatGPT AI
# This code is written in Terraform, which is a tool for provisioning infrastructure as code. The code is defining the provisioning of a virtual private server (VPS) on the Linode cloud platform.
# The first block of code specifies that the Linode provider for Terraform, version 1.27.1, is being used.
# The following block of code sets the Linode API key as a provider variable, which is used to authenticate with the Linode API.
# The next block of code creates a resource of type "linode_instance" and names it "terraform-web". This resource represents the virtual private server that will be provisioned on the Linode platform. The properties of this resource are being set using variables, such as "linode_image", "linode_image_label", "linode_image_group", "linode_image_deployment_region" and "linode_image_type".
# The following block of code defines variables that are used to set the properties of the "linode_instance" resource. "linode_api_key", "public_ssh_key" and "root_pwd" are sensitive variables, which means that their values should be protected and not exposed in plain text.
# Finally, the code creates a Linode instance with the specified properties and deploys the Linux Node on the cloud by script.

# Simple Human coding: alteration of functions by AI will be indicated as well
terraform {
  required_providers {
    linode = {
      source = "linode/linode"
      version = "1.27.1"
    }
  }
}

provider "linode" {
  token = "linode_api_key"
}

resource "linode_instance" "terraform-web" {
        image           = var.linode_image
        label           = var.linode_image_label
        group           = var.Linode_image_group
        region          = var.linode_image_deployment_region
        type            = var.linode_image_type
        authorized_keys = [ var.public_ssh_key ]
        root_pass       = var.root_pwd
}

# System environment exported variable
variable "linode_api_key" {
  description = "Linode PaaS API key"
  type        = string
  sensitive   = true
}

# System environment exported variable
variable "public_ssh_key" {
  description = "Linode nodes public ssh"
  type        = string
  sensitive   = true
}

# System environment exported variable
variable "root_pwd" {
  description = "Node root ssh password"
  type        = string
  sensitive   = true
}
